#FROM almalinux:9
#CMD can be over written easily through command line

#CMD ["ping", "google.com"]   
#ENTRYPOINT ["ping", "google.com"]


#So now the combo & Final code is as below

FROM almalinux:9
CMD ["google.com"]
ENTRYPOINT ["ping"]