#CMD can be override through command line,Used as I/p or Options in combo of ENTRYPOINT.
#ENTRYPOINT Can't be override,As it is locks-we use for command in combo of CMD.

#FROM almalinux:9
#CMD ["ping", "google.com"] 

#ENTRYPOINT ["ping", "google.com"]


#So now the combo & Final code is as below

FROM almalinux:9
CMD ["google.com"]
ENTRYPOINT ["ping"]